[package]
name = "config"
version = "0.1.0"
edition.workspace = true

[dependencies]
action = { workspace = true }
config-macros = { workspace = true }
crossterm = { workspace = true }
include_dir = { workspace = true }
jiff = { workspace = true }
kdl = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
insta = { workspace = true }
